USE `javawork`;

ALTER TABLE JOB DROP COLUMN JOB_TYPE;
ALTER TABLE JOB ADD JOB_TYPE ENUM('Full Time','Part Time') NOT NULL DEFAULT  'Full Time';

ALTER TABLE JOB DROP COLUMN APPLIED_COUNT;
ALTER TABLE JOB ADD APPLIED_COUNT INT(11) NOT NULL DEFAULT  0;